[project]
name = "pilake"
version = "0.9.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.43.2",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = 'home-index'
url = "http://192.168.0.29:8080/simple/"
publish-url = "http://192.168.0.29:8080/"

[dependency-groups]
dev = [
    "ruff>=0.15.12",
    "ty>=0.0.33",
]
